### ISSUE TITLE
为啥不用vite

### ISSUE THREAD

**Issue by lhlyu** [advanced-frontend-lesson/hefeng-ui#8]
RT.
希望能看到预览地址

**Comment by hefeng6500** [comment]
Dear lhlyu，rollup 或许更适合多包管理一些，ui 组件库文档可以使用 vite 试验一下，期望 @lhlyu 的 pull request。目前文档 website还不够完善，后续整个组件库发布了会出预览地址哈。

**Comment by leonyangdev** [comment]
> RT.
> 希望能看到预览地址

Dear lhlyu，rollup 或许更适合多包管理一些，ui 组件库文档可以使用 vite 试验一下，期望 @lhlyu 的 pull request。目前文档 website还不够完善，后续整个组件库发布了会出预览地址哈。
